spring:
  redis:
    host: localhost
    port: 6379
    database: 2
  datasource:
    url: jdbc:postgresql://localhost:3306/demo
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver



# mybatis-plus相关配置
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


dubbo:
  registry:
    address: zookeeper://localhost:2181
  application:
    name: usercenter
  protocol:
    name: dubbo
    port: 20883