version: '3'
services:
  nacos:
    restart: always
    image: nacos/nacos-server:v2.2.2-slim
    # 容器名称
    container_name: nacos
    # 端口映射
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    # 容器权限
    privileged: true
    # 参数设置
    environment:
      JVM_XMS: 128m
      JVM_XMX: 128m
      JVM_MS: 64m
      JVM_MMS: 64m
      MODE: standalone
      NACOS_REPLICAS: 1
      PREFER_HOST_MODE: ip
    volumes:
      - ./logs:/home/nacos/logs
      - ./plugins:/home/nacos/plugins
      - ./data:/home/nacos/data
      - ./config/application.properties:/home/nacos/conf/application.properties
    networks:
      - dev
      # dev:  # 自定义的网桥名称
      #   aliases: # 用来设置服务别名，相同的服务可以在不同的网络上有不同的别名
      #     - nacos

networks:
  dev:
    external: true
      
