version: "3"
services:
    mysql8:
      image: mysql:8.0
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        
      command: 
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      ports:
        - "3306:3306"
      volumes:
        - "./data/data:/var/lib/mysql"
        - "./data/logs:/var/log/mysql"
      restart: always
      networks:
        - mysql8_net
      container_name: mysql8
networks:
  mysql8_net:
    driver: bridge
